Updates to PoWEx vocabulary and common vocabularies
INCOMS/vc-specs pull request #5
Opened 2021-12-22 18:38 UTC by kochhar

Updates
1. Refactored CredentialBase to reference VC and Common vocabularies
2. Updated Common vocabularies to reference schema.org 
3. Updated PoWEx vocabulary to reference CredentialBase and Common vocabularies

2021-12-24 10:36 UTC, pramodkvarma requested changes
I have commented during review. Can you please check my comments? @kochhar ? Thanks.

2021-12-24 10:36 UTC, pramodkvarma commented on common/CertificateBase.jsonld
> +        "sunvc": "https://github.com/sunbird-specs/vc-specs#",
You can prefix with 'sb' instead of 'sun' as in 'sbvc' instead of 'sunvc'

2021-12-24 10:36 UTC, pramodkvarma commented on work/powex.jsonld
> +        "address": { "@id": "schema:address", "@type": "sunvc:Address" },
Some SBVC core objects like 'fullname' starts with small letter while objects like 'Address' starts with capital. Any reason? If it needs fix can you please fix it aa well @kochhar ? Thanks. @dileepbapat

2021-12-24 10:36 UTC, pramodkvarma commented on work/powex.jsonld
> +        "worksAs": { "@id": "powex:worksAs", "@type": "powex:OccupationalRole" },
Is powex local object for proof of work? Could we reference it as 'sbvc.powex'? @kochhar

2022-03-05 21:47 UTC, merged

2022-03-05 21:48 UTC, pramodkvarma commented
Btw, I moved vc-specs repo into a top level org called INCOMS on Github where all kinds of VC models can be worked out. @kochhar your object namespaces will need update. Can you please do?

2022-03-09 12:10 UTC, kochhar commented
Definitely. I will update the references and send a PR

On Sun, 6 Mar, 2022, 3:18 AM Pramod Varma, ***@***.***> wrote:

> Btw, I moved vc-specs repo into a top level org called INCOMS on Github
> where all kinds of VC models can be worked out. @kochhar
> <https://github.com/kochhar> your object namespaces will need update. Can
> you please do?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/INCOMS/vc-specs/pull/5#issuecomment-1059836204>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAZLKURGJNAOLJY5RLK7ADU6PJEXANCNFSM5KTE3SPQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-09 12:14 UTC, pramodkvarma commented
Thanks a lot @kochhar